package content

import "dead-drop-dispatch/internal/game"

func JobTemplates() []game.JobTemplate {
	return []game.JobTemplate{
		{
			ID:              "clinic_rush",
			Title:           "Clinic rush",
			ClientMessage:   "Cooler runs hot after sundown. Keep it moving.",
			Cargo:           game.CargoMedicalCooler,
			Faction:         FactionClinic,
			BasePayout:      180,
			BaseDeadline:    1,
			Modifiers:       []string{"fragile", "cold chain"},
			RiskFactors:     []string{"cargo integrity", "client urgency"},
			PreferredRoutes: []game.RouteType{game.RouteMarketWeave, game.RouteServiceTunnels, game.RouteFloodline},
		},
		{
			ID:              "quiet_data_handoff",
			Title:           "Quiet data hand-off",
			ClientMessage:   "No names, no calls, no curious looks.",
			Cargo:           game.CargoDataShard,
			Faction:         FactionAsterion,
			BasePayout:      140,
			BaseDeadline:    2,
			Modifiers:       []string{"encrypted", "silent client"},
			RiskFactors:     []string{"corporate trace"},
			PreferredRoutes: []game.RouteType{game.RouteServiceTunnels, game.RouteDroneCorridor, game.RouteMainArtery},
		},
		{
			ID:              "witness_transfer",
			Title:           "Witness transfer",
			ClientMessage:   "They talk when scared. Do not let them get scared.",
			Cargo:           game.CargoWitness,
			Faction:         FactionHelix,
			BasePayout:      260,
			BaseDeadline:    2,
			Modifiers:       []string{"talking cargo", "panic risk"},
			RiskFactors:     []string{"witness nerves", "checkpoint exposure"},
			PreferredRoutes: []game.RouteType{game.RouteMarketWeave, game.RouteMainArtery, game.RouteServiceTunnels},
		},
		{
			ID:              "prototype_lift",
			Title:           "Prototype lift",
			ClientMessage:   "The case pings if opened. Nobody opens it.",
			Cargo:           game.CargoCorporatePrototype,
			Faction:         FactionAsterion,
			BasePayout:      320,
			BaseDeadline:    2,
			Modifiers:       []string{"valuable", "traceable"},
			RiskFactors:     []string{"corporate trackers", "intercept interest"},
			PreferredRoutes: []game.RouteType{game.RouteDroneCorridor, game.RouteServiceTunnels, game.RouteFloodline},
		},
		{
			ID:              "union_favor",
			Title:           "Union favor",
			ClientMessage:   "Move the bag and the docks remember your name.",
			Cargo:           game.CargoContrabandPackage,
			Faction:         FactionUnion,
			BasePayout:      160,
			BaseDeadline:    3,
			Modifiers:       []string{"dock codes", "favor marker"},
			RiskFactors:     []string{"union politics"},
			PreferredRoutes: []game.RouteType{game.RouteFloodline, game.RouteMarketWeave, game.RouteMainArtery},
		},
		{
			ID:              "dirty_evidence",
			Title:           "Dirty evidence",
			ClientMessage:   "Chain of custody broke. Make sure the trail does too.",
			Cargo:           game.CargoDataShard,
			Faction:         FactionHelix,
			BasePayout:      210,
			BaseDeadline:    2,
			Modifiers:       []string{"hot evidence", "chain of custody"},
			RiskFactors:     []string{"security audit", "bad witnesses"},
			PreferredRoutes: []game.RouteType{game.RouteMainArtery, game.RouteServiceTunnels, game.RouteDroneCorridor},
		},
		{
			ID:              "decoy_package",
			Title:           "Decoy package",
			ClientMessage:   "It is meant to be seen, just not held.",
			Cargo:           game.CargoContrabandPackage,
			Faction:         FactionUnion,
			BasePayout:      120,
			BaseDeadline:    1,
			Modifiers:       []string{"decoy", "heat sink"},
			RiskFactors:     []string{"attention magnet"},
			PreferredRoutes: []game.RouteType{game.RouteMainArtery, game.RouteMarketWeave},
		},
		{
			ID:              "split_route",
			Title:           "Split route",
			ClientMessage:   "Two doors, one package, no second chances.",
			Cargo:           game.CargoDataShard,
			Faction:         FactionClinic,
			BasePayout:      190,
			BaseDeadline:    3,
			Modifiers:       []string{"two contacts", "route drift"},
			RiskFactors:     []string{"destination complexity"},
			PreferredRoutes: []game.RouteType{game.RouteMarketWeave, game.RouteFloodline, game.RouteServiceTunnels, game.RouteMainArtery},
		},
		{
			ID:              "curfew_run",
			Title:           "Curfew run",
			ClientMessage:   "The clinic clock is louder than the patrol sirens.",
			Cargo:           game.CargoMedicalCooler,
			Faction:         FactionClinic,
			BasePayout:      230,
			BaseDeadline:    1,
			Modifiers:       []string{"after curfew", "clinic clock"},
			RiskFactors:     []string{"curfew patrols", "medical spoilage"},
			PreferredRoutes: []game.RouteType{game.RouteServiceTunnels, game.RouteFloodline, game.RouteDroneCorridor},
		},
		{
			ID:              "bad_client",
			Title:           "Bad client",
			ClientMessage:   "The client is lying. The money is not.",
			Cargo:           game.CargoCorporatePrototype,
			Faction:         FactionAsterion,
			BasePayout:      280,
			BaseDeadline:    2,
			Modifiers:       []string{"client lies", "unstable terms"},
			RiskFactors:     []string{"betrayal risk", "unclear package"},
			PreferredRoutes: []game.RouteType{game.RouteMarketWeave, game.RouteMainArtery, game.RouteDroneCorridor},
		},
	}
}
